In [2]:
# Axis Test
import numpy as np

DATA_EXAMPLE = np.array([[ 1., 1,  1],
               [ 2,  2,  2],
               [ 3, 3, 3]])

In [4]:
DATA_EXAMPLE.mean(axis=0)

array([ 2.,  2.,  2.])

In [6]:
DATA_EXAMPLE.mean(axis=1)

array([ 1.,  2.,  3.])

In [7]:
# Axis Test

DATA_EXAMPLE = np.array([[[ 1., 1,  1],
               [ 1,  1,  1],
               [ 1, 1, 1]],
                       [[ 2., 2,  2],
               [ 2,  2,  2],
               [ 2, 2, 2]],
                       [[ 3, 3,  3],
               [ 3,  3,  3],
               [ 3, 3, 3]]])

In [9]:
DATA_EXAMPLE.mean(axis=0)

array([[ 2.,  2.,  2.],
       [ 2.,  2.,  2.],
       [ 2.,  2.,  2.]])

In [10]:
DATA_EXAMPLE.mean(axis=1)

array([[ 1.,  1.,  1.],
       [ 2.,  2.,  2.],
       [ 3.,  3.,  3.]])

In [11]:
DATA_EXAMPLE.mean(axis=2)

array([[ 1.,  1.,  1.],
       [ 2.,  2.,  2.],
       [ 3.,  3.,  3.]])