In [3]:
# Data from https://archive.ics.uci.edu/ml/datasets/Breast+Cancer+Wisconsin+(Diagnostic)

In [47]:
import pandas as pd
import numpy as np

In [14]:
columns = ["id", "diagnosis"] + [str("r"+str(i)) for i in range(30)]
df = pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/breast-cancer-wisconsin/wdbc.data", names=columns)
df.head(5)

id diagnosis     r0     r1      r2      r3       r4       r5      r6  \
0    842302         M  17.99  10.38  122.80  1001.0  0.11840  0.27760  0.3001   
1    842517         M  20.57  17.77  132.90  1326.0  0.08474  0.07864  0.0869   
2  84300903         M  19.69  21.25  130.00  1203.0  0.10960  0.15990  0.1974   
3  84348301         M  11.42  20.38   77.58   386.1  0.14250  0.28390  0.2414   
4  84358402         M  20.29  14.34  135.10  1297.0  0.10030  0.13280  0.1980   

        r7   ...       r20    r21     r22     r23     r24     r25     r26  \
0  0.14710   ...     25.38  17.33  184.60  2019.0  0.1622  0.6656  0.7119   
1  0.07017   ...     24.99  23.41  158.80  1956.0  0.1238  0.1866  0.2416   
2  0.12790   ...     23.57  25.53  152.50  1709.0  0.1444  0.4245  0.4504   
3  0.10520   ...     14.91  26.50   98.87   567.7  0.2098  0.8663  0.6869   
4  0.10430   ...     22.54  16.67  152.20  1575.0  0.1374  0.2050  0.4000   

      r27     r28      r29  
0  0.2654  0.4601  0.11890  
1  0.1860  0.2750  0.08902  
2  0.2430  0.3613  0.08758  
3  0.2575  0.6638  0.17300  
4  0.1625  0.2364  0.07678  

[5 rows x 32 columns]

In [39]:
X = df.loc[:,columns[2:]].values
Y_raw = df.loc[:,columns[1]].values
X[:2],Y_raw[:2]

(array([[  1.79900000e+01,   1.03800000e+01,   1.22800000e+02,
           1.00100000e+03,   1.18400000e-01,   2.77600000e-01,
           3.00100000e-01,   1.47100000e-01,   2.41900000e-01,
           7.87100000e-02,   1.09500000e+00,   9.05300000e-01,
           8.58900000e+00,   1.53400000e+02,   6.39900000e-03,
           4.90400000e-02,   5.37300000e-02,   1.58700000e-02,
           3.00300000e-02,   6.19300000e-03,   2.53800000e+01,
           1.73300000e+01,   1.84600000e+02,   2.01900000e+03,
           1.62200000e-01,   6.65600000e-01,   7.11900000e-01,
           2.65400000e-01,   4.60100000e-01,   1.18900000e-01],
        [  2.05700000e+01,   1.77700000e+01,   1.32900000e+02,
           1.32600000e+03,   8.47400000e-02,   7.86400000e-02,
           8.69000000e-02,   7.01700000e-02,   1.81200000e-01,
           5.66700000e-02,   5.43500000e-01,   7.33900000e-01,
           3.39800000e+00,   7.40800000e+01,   5.22500000e-03,
           1.30800000e-02,   1.86000000e-02,   1.34000

In [41]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
Y = le.fit_transform(Y_raw)
Y[:30], Y_raw[:30]

(array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1,
        1, 1, 1, 1, 1, 1, 1], dtype=int64),
 array(['M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M',
        'M', 'M', 'M', 'M', 'M', 'M', 'B', 'B', 'B', 'M', 'M', 'M', 'M',
        'M', 'M', 'M', 'M'], dtype=object))

In [45]:
len(Y)

569

In [54]:
random_index = np.arange(569)
np.random.shuffle(random_index)
random_index[:100]

array([ 58, 231, 432, 481,   5, 532, 545,  82, 120, 294, 136, 405, 435,
       143, 205, 284, 225, 388, 197, 482, 411, 258, 469, 333, 518, 479,
       473, 415, 552, 247, 105,  39,  71, 408, 100, 147, 497, 107, 359,
        87, 332, 235,  99, 401, 347, 179, 562, 451, 282, 381,  23, 287,
        27,  11, 134, 362, 399, 238, 309, 542, 527, 440, 138, 140, 498,
       208, 414, 476, 407, 475, 393, 211, 506, 339,  81, 118, 130, 237,
       286, 500,  96, 567, 173, 530,  43, 409, 311, 113, 558, 341, 366,
       296, 281,  26, 443, 273, 457, 102, 551, 244])

In [66]:
training_index = random_index[:int(len(Y) * .8)]
test_index = random_index[int(len(Y) * .8):] 

In [69]:
x_train = X[training_index]
x_test = X[test_index]
y_train  = Y[training_index]
y_test = Y[test_index]

IndexError: failed to coerce slice entry of type numpy.ndarray to integer